### ISSUE TITLE
java.lang.VerifyError on at least two different Android 4 phones (after successful login).

### ISSUE THREAD

**Issue by sannysanoff** [facebook/makeitopen#22]
E/AndroidRuntime( 7799): FATAL EXCEPTION: main
E/AndroidRuntime( 7799): java.lang.VerifyError: com/facebook/f8/a/c
E/AndroidRuntime( 7799): 	at com.facebook.f8.F8MainActivity.onCreate(F8MainActivity.java:39)
E/AndroidRuntime( 7799): 	at android.app.Activity.performCreate(Activity.java:4479)
E/AndroidRuntime( 7799): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1050)
E/AndroidRuntime( 7799): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2188)
E/AndroidRuntime( 7799): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2263)
E/AndroidRuntime( 7799): 	at android.app.ActivityThread.access$600(ActivityThread.java:145)
E/AndroidRuntime( 7799): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1258)
E/AndroidRuntime( 7799): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 7799): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime( 7799): 	at android.app.ActivityThread.main(ActivityThread.java:4834)
E/AndroidRuntime( 7799): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 7799): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 7799): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:816)
E/AndroidRuntime( 7799): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:583)
E/AndroidRuntime( 7799): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by sannysanoff** [comment]
wrong repo, sorry
